# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_nav',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5bfc\u822a'),
        ),
    ]
